definitions:
  api.RegisterReq:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  api.RegisterRes:
    properties:
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: registers a new user
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.RegisterRes'
      summary: Register
      tags:
      - Auth
swagger: "2.0"
